# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install node'
  
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    dir
    echo See https://aka.ms/yaml
  displayName: 'list directory and run a multi-line script'

- script: |
    workingDirectory: /api
    dir
    npm install
    npm test
  displayName: 'npm install test in api'

- script: |
    workingDirectory: /client
    dir
    npm install
    npm test
  displayName: 'npm install test in client'
